### ISSUE TITLE
Create project roadmap

### ISSUE THREAD

**Issue by antonleliuk** [antonleliuk/media-library#1]

**Comment by antonleliuk** [comment]
1. Users management

- [ ] Users infrastructure (tables, services)

- [ ] Security mechanism (roles and privileges)

- [ ] Create administrator

1.1. UI

- [ ] Login page

    - [ ] Forgot / change password

    - [ ] Remember me 

- [ ] User list

- [ ] User CRUD

- [ ] Administrator can create new users

2. Media library

- [ ] Library CRUD

- [ ] Sync files and folders

3. Books library

3.1. Integration with FbReader

**Comment by antonleliuk** [comment]
#2
